"""
Django settings for sms_backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url # Import for PostgreSQL database configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY WARNING: keep the secret key used in production secret! ---
# For production, load from environment variable
SECRET_KEY = os.environ.get('SECRET_KEY', '8z!$g8vhqh=cos8d5x*q&wi50e!5e+g6^0i^(@)tyq13_t-gh$') # Replace with a strong default or ensure it's always set in Render env

# --- SECURITY WARNING: don't run with debug turned on in production! ---
DEBUG = 'RENDER' not in os.environ # Automatically set DEBUG to False on Render

ALLOWED_HOSTS = []
# Render sets the "RENDER" environment variable to "true"
if 'RENDER' in os.environ:
    ALLOWED_HOSTS += [os.environ.get('RENDER_EXTERNAL_HOSTNAME')] # Add Render's hostname
else:
    ALLOWED_HOSTS += ['127.0.0.1', 'localhost'] # For local development


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'students',
    'whitenoise.runserver_nostatic', # Add for local static files during development
    'whitenoise.middleware.WhiteNoiseMiddleware', # Add for serving static files in production
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be listed directly after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware', # Add this for static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sms_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR], # This allows Django to find index.html in the project root
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sms_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL in production (on Render)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# This is the directory where `collectstatic` will gather all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For local development, if you have static files outside of app/static/ folders
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'), # Uncomment if you have a top-level /static/ folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# In production, restrict this to your frontend's Render URL
if 'RENDER' in os.environ:
    # Replace with your actual frontend Render.com URL after deployment
    CORS_ALLOWED_ORIGINS = [
        f"https://{os.environ.get('RENDER_EXTERNAL_HOSTNAME').replace('-backend', '-frontend')}", # Example: if backend is X-backend, frontend is X-frontend
        # Or hardcode if you know it: "https://your-frontend-name.onrender.com"
    ]
    # Allow credentials if needed (e.g., for sessions/cookies, though generally not for simple APIs)
    CORS_ALLOW_CREDENTIALS = False # Change to True if your frontend needs to send cookies/auth headers
else:
    CORS_ALLOW_ALL_ORIGINS = True # Keep for local development